name: test

on: [ push, pull_request ]

env:
  MAVEN_OPTS: -Xmx1024M -Xss128M -XX:+CMSClassUnloadingEnabled

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build
        run:
          mvn clean install -Dtest='!org.mycore.sru.SRUConnectorFactoryTest#testK10Plus'
